In [9]:
import numpy as np

#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
list1 = np.arange(0,21,1)
print("1. 等差數列，首數為0，尾數為20，公差為1:")
print(list1,"\n")

#2.呈上題，將以上數列取出偶數。
print ("2. 將1.的數列取出偶數:")
list2 = np.arange(0,21,2)  
print(list2,"\n")

#3.呈1題，將數列取出3的倍數。
print ("3. 將1.的數列取出3的倍數:")
list3 = np.arange(3,21,3)
print(list3)

1. 等差數列，首數為0，尾數為20，公差為1:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

2. 將1.的數列取出偶數:
[ 0  2  4  6  8 10 12 14 16 18 20] 

3. 將1.的數列取出3的倍數:
[ 3  6  9 12 15 18]
