In [13]:
import numpy as np

#原矩陣
array1 = np.array([[10, 8], [3, 5]])
print("array1:\n",array1,"\n")

#1.運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#反矩陣
array1_inv = np.linalg.inv(array1)
print("1.計算上列array1之反矩陣\n",array1_inv)
# 反矩陣X原矩陣
array1_dot = array1_inv@array1
print("  反矩陣X原矩陣\n",array1_dot)   #用法同 array1_inv.dot(array1)
#補充說明:單位矩陣：n行n列,且主對角線上都是1,其他位置都是0的矩陣
array_eye = np.eye(2)  # 創造一個單位矩陣，2X2單位矩陣也可用 np.identity(2)
#print(array_eye)
print ("=>是否為單位矩陣:",np.all(np.equal(array1_dot, array_eye)),"\n") #與array1_dot比對是否一致

#2.運用上列array計算特徵值、特徵向量?
array1_value, array1_vector = np.linalg.eig(array1)
print("2.array1特徵值(eigenvalues):\n",array1_value)  #特徵值也可以用np.linalg.eigvals(array1)
# 特徵向量(eigenvectors)
print("  array1特徵向量(eigenvectors):\n",array1_vector,"\n")

# #驗證特徵值分解
# smat=np.zeros((2,2))
# smat= np.diag(array1_value)
# result=np.allclose( array1, np.dot(array1_vector, np.dot(smat, np.linalg.inv(array1_vector))))
# #對比兩個矩陣的各個元素，若一致則返回True
# print(" 驗證特徵值分解:",result,"\n")

#3.運用上列array計算SVD? 
#Singular Value Decomposition (SVD) (奇異值分解)
u, sigma, vh = np.linalg.svd(array1)
print("3.運用上列array計算SVD")
print("U\n",u)
print("Sigma\n",sigma)
print("Vh\n",vh)

# #驗證奇異值分解
# smat=np.zeros((2,2))
# smat[:2,:2]= np.diag(sigma)
# print('\n 奇異矩陣：\n',smat)
# result=np.allclose(array1, np.dot(u, np.dot(smat, vh)))#對比兩個矩陣的各個元素，若一致則返回True
# print(" 驗證奇異值分解:",result)

array1:
 [[10  8]
 [ 3  5]] 

1.計算上列array1之反矩陣
 [[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
  反矩陣X原矩陣
 [[1.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00]]
=>是否為單位矩陣: False 

2.array1特徵值(eigenvalues):
 [13.  2.]
  array1特徵向量(eigenvectors):
 [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]] 

3.運用上列array計算SVD
U
 [[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
Sigma
 [13.94721714  1.86417116]
Vh
 [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
